### ISSUE TITLE
Signs meta gone on //undo //redo

### ISSUE THREAD

**Issue by M9GLiquid** [IntellectualSites/PlotSquared#1329]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/axikerisuz

**Description of the problem:**
Sign information (Meta) dissapear when you paste something above it/on it and then do undo to the original.

Undo does not make the signs properly

**How to replicate**:
Make a sign with value, paste a schematic over it, do /undo, RESULT the sign will be blank

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Not a PlotSquared bug. Try updating FastAsyncWorldEdit.
